# We apply nginx LoadBalancer service to distribute a traffic
# the most efficient way between the pods
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  # Declare ports for the outside world
  ports:
      # We configure same port as in containers
    - name: http
      protocol: TCP
      port: 80 # e.g. http://129.91.12.312:80 
      targetPort: 80
  selector:
    app: nginx-deployment