apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: django-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/cfe-k8s-nikita/django-k8s-web:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: cfe-k8s-nikita