apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iac-python-deployment
  template:
    metadata:
      labels:
        app: iac-python-deployment
    spec:
      containers:
        - name: iac-python
          # this image will come directly from a DockerHub
          # it's public image from CodingEnterpreneurs
          image: codingforentrepreneurs/iac-python:latest
          # Ports are similar that we define in entrypoint.sh
          # So here we can also use Environment Variable like there
          env:
            - name: PORT
              value: "8181"
          ports:
            - containerPort: 8181

--- 

# We apply nginx LoadBalancer service to distribute a traffic
# the most efficient way between the pods
apiVersion: v1
kind: Service
metadata:
  name: iac-python-service
spec:
  type: LoadBalancer
  # Declare ports for the outside world
  ports:
      # We configure same port as in containers
    - name: http
      protocol: TCP
      port: 80 # e.g. http://129.91.12.312:80 
      # port of target container
      targetPort: 8181
  selector:
    app: iac-python-deployment